pipeline {
  agent none
  environment {
    PATH = "/usr/local/bin:/usr/bin:/bin:/usr/bin/docker"
  }
  stages {
    stage('Build') {
      agent {
         docker { image 'node:16-alpine' }
       } 
       steps {
         sh 'node --version'
       }
    }
  }
}
