pipeline {
  agent any
  environment {
    PATH = "/usr/local/bin:/usr/bin:/bin:/usr/bin/docker"
  }
  stages {
    stage('Build') {
       steps {
         sh 'docker --version'
       }
    }
  }
}
